name = "Forever - Reimagined"
author = "FyerPower"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e10a6de16eb9b63423eadecfca7ec2db3164b336bd9f100646977cb830b14f5f"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
