name = "Forever - Reimagined"
author = "FyerPower"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d7110dadb465a1199f08ed70eaadc34aefa8b3c035bc498db5dd91852ea99ec"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
