name = "Forever - Reimagined"
author = "FyerPower"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a31916929268ef2f10356a41ff290c17423772666ca6248b403bc6fe6d5efbbe"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
