name = "FyerPower's Community Vanilla+"
author = "FyerPower"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcf903ea93bac25a40408d0290aa5bf39c7563b00d15604fabd19fc61b950346"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
