name = "Forever - Reimagined"
author = "FyerPower"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8763c47af83972a23751a04d69cded730176e0b0d49f9bbe438ac54ffd55bff1"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
